# Book settings
title: Practica 2 — Documentación del Proyecto
author: Tu equipo

root: index

execute:
  execute_notebooks: off

bibtex_bibfiles:
  - references.bib

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: "/practica1"   

repository:
  url: https://github.com/PracticaJuanyLuis/practica1
  path_to_book: docs/libro
  branch: main

