# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/PracticaJuanyLuis/practica1
  path_to_book: docs/libro
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: /practica1
